gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'ALL_WINDOWS'
gsettings set org.gnome.shell.extensions.dash-to-dock animation-time 0.20
gsettings set org.gnome.shell.extensions.dash-to-dock hide-delay 0.15

gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.35
gsettings set org.gnome.shell.extensions.dash-to-dock always-center-icons true
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
gsettings set org.gnome.shell.extensions.dash-to-dock show-icons-emblems false
gsettings set org.gnome.shell.extensions.dash-to-dock show-icons-notifications-counter false

gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-customize-running-dots true
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-color '#D86050'
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-color '#A73732'
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-width 1
