export GSETTINGS_SCHEMA_DIR="$HOME/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/schemas"

gsettings set org.gnome.shell.extensions.hidetopbar mouse-sensitive true
gsettings set org.gnome.shell.extensions.hidetopbar enable-intellihide false
gsettings set org.gnome.shell.extensions.hidetopbar animation-time-autohide 0.25
gsettings set org.gnome.shell.extensions.hidetopbar animation-time-overview 0.35
gsettings set org.gnome.shell.extensions.hidetopbar hot-corner false
gsettings set org.gnome.shell.extensions.hidetopbar keep-round-corners true
